import React, { useEffect, useState } from "react";
import { ArrowLeft, DollarSign, Hospital, Loader2, MapPin, Mic, Search, ShieldCheck, Stethoscope } from "lucide-react";

const headers = () => ({ "Content-Type": "application/json", ...(localStorage.getItem("token") ? { Authorization: `Bearer ${localStorage.getItem("token")}` } : {}) });
const Field = ({ label, children }) => <label className="block text-xs font-medium text-stone-600">{label}{children}</label>;
const prettyTime = (value) => { const [h, m] = String(value || "").split(":").map(Number); return Number.isFinite(h) ? `${h % 12 || 12}:${String(m).padStart(2, "0")} ${h >= 12 ? "PM" : "AM"}` : value; };
const today = () => new Date().toISOString().slice(0, 10);
const futureSchedules = (schedules) => schedules.filter((item) => item.date && item.date >= today());
const datesFor = (schedules) => [...new Set(futureSchedules(schedules).map((item) => item.date))].sort();
const timesFor = (schedules, date) => [...new Set(futureSchedules(schedules).filter((item) => item.date === date).flatMap((item) => { const [sh, sm] = item.start_time.split(":").map(Number); const [eh, em] = item.end_time.split(":").map(Number); const values = []; for (let minute = sh * 60 + sm; minute < eh * 60 + em; minute += Number(item.slot_duration) || 30) values.push(`${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`); return values; }))].sort();
const displayDate = (value) => new Date(`${value}T00:00:00`).toLocaleDateString(undefined, { day: "numeric", month: "long", year: "numeric" });
const isSpecialtyOnDuty = (hospital, specialty) => {
  if (!specialty) return true;
  const configuredSpecialty = Object.keys(hospital.specialist_availability || {}).find((item) => item.trim().toLowerCase() === specialty.trim().toLowerCase());
  return configuredSpecialty === undefined || hospital.specialist_availability[configuredSpecialty] !== false;
};

export default function HospitalDirectory({ currentUser, initialHospital, onInitialHospitalHandled }) {
  const [filters, setFilters] = useState({ search: "", location: "", specialist: "", treatment: "", maxPrice: 5000 });
  const [hospitals, setHospitals] = useState([]), [selected, setSelected] = useState(null), [detailLoading, setDetailLoading] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(""), [listening, setListening] = useState(false);
  useEffect(() => {
    if (!initialHospital?.id) return;
    let active = true;
    const loadSelectedHospital = async () => {
      setSelected(null);
      setDetailLoading(true);
      setError("");
      try {
        const response = await fetch(`/api/hospitals/${encodeURIComponent(initialHospital.id)}`);
        const data = await response.json();
        if (!response.ok) throw new Error(data.detail || "Could not load the selected hospital.");
        if (active) setSelected(data);
      } catch (err) {
        if (active) setError(err.message);
      } finally {
        if (active) {
          setDetailLoading(false);
          onInitialHospitalHandled?.();
        }
      }
    };
    loadSelectedHospital();
    return () => { active = false; };
  }, [initialHospital?.id]);
  useEffect(() => { const load = async () => { setLoading(true); try { const params = new URLSearchParams({ search: filters.search, max_price: String(filters.maxPrice) }); ["location", "specialist", "treatment"].forEach((key) => filters[key] && params.set(key, filters[key])); const response = await fetch(`/api/hospitals?${params}`); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Could not load hospitals."); setHospitals(data); setError(""); } catch (err) { setError(err.message); } finally { setLoading(false); } }; load(); }, [filters]);
  const update = (key, value) => setFilters((current) => ({ ...current, [key]: value }));
  const voice = () => { const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!Recognition) return setError("Voice search is not supported by this browser."); const recognition = new Recognition(); recognition.lang = "en-IN"; recognition.onstart = () => setListening(true); recognition.onend = () => setListening(false); recognition.onresult = (event) => update("search", event.results[0][0].transcript); recognition.start(); };
  const specialties = [...new Set(hospitals.flatMap((hospital) => (hospital.specialist_profiles || []).map((item) => item.specialization).filter(Boolean)))];
  const treatments = [...new Set(hospitals.flatMap((hospital) => (hospital.treatments || []).map((item) => item.name).filter(Boolean)))];
  if (detailLoading) return <p className="mx-auto max-w-5xl px-4 py-12 text-center text-sm text-stone-500">Loading hospital details...</p>;
  if (selected) return <Details hospital={selected} currentUser={currentUser} onBack={() => setSelected(null)} />;
  return <div className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><h1 className="text-2xl font-semibold">Find care that fits</h1><div className="mt-6 rounded-2xl border border-emerald-100 bg-white p-4 shadow-sm"><div className="flex gap-2"><input value={filters.search} onChange={(e) => update("search", e.target.value)} placeholder="Search hospitals, specialties, treatments, or cities" className="w-full rounded-xl border border-stone-200 py-3 px-3 text-sm" /><button onClick={voice} aria-label="Search by voice" className={`flex h-11 w-11 items-center justify-center rounded-xl ${listening ? "bg-red-600" : "bg-emerald-700"} text-white`}><Mic className="h-4 w-4" /></button></div><div className="mt-3 grid gap-3 sm:grid-cols-4"><Field label="Location"><input value={filters.location} onChange={(e) => update("location", e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm" /></Field><Field label="Treatment"><select value={filters.treatment} onChange={(e) => update("treatment", e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="">All treatments</option>{treatments.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Specialist"><select value={filters.specialist} onChange={(e) => update("specialist", e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-2 text-sm"><option value="">All specialists</option>{specialties.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label={`Maximum price: ₹${filters.maxPrice}`}><input type="range" min="0" max="10000" step="500" value={filters.maxPrice} onChange={(e) => update("maxPrice", Number(e.target.value))} className="mt-3 w-full accent-emerald-700" /></Field></div></div>{error && <p className="mt-4 text-sm text-red-700">{error}</p>}{loading ? <p className="py-12 text-center text-sm text-stone-500">Loading hospitals...</p> : <div className="mt-6 grid gap-4 md:grid-cols-2">{hospitals.map((hospital) => <article key={hospital.id} className="rounded-2xl border bg-white p-5"><Hospital className="h-6 w-6 text-emerald-700" /><h2 className="mt-3 font-semibold">{hospital.name}</h2><p className="mt-1 text-xs text-stone-500"><MapPin className="mr-1 inline h-3.5 w-3.5" />{hospital.address}</p><p className="mt-3 text-sm text-stone-600">{hospital.description || "Description not configured by hospital staff."}</p><button onClick={() => setSelected(hospital)} className="mt-4 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white">View hospital</button></article>)}</div>}</div>;
}

function Details({ hospital, currentUser, onBack }) {
  const [booking, setBooking] = useState(null), [message, setMessage] = useState("");
  const activeTreatments = (hospital.treatments || []).filter((item) => isSpecialtyOnDuty(hospital, item.specialization));
  return <div className="mx-auto max-w-5xl px-4 py-8"><button onClick={onBack} className="mb-5 flex items-center gap-1 text-sm text-emerald-700"><ArrowLeft className="h-4 w-4" />Back</button><section className="rounded-2xl border bg-white p-5"><h1 className="text-2xl font-semibold">{hospital.name}</h1><p className="mt-2 text-sm text-stone-500">{hospital.address}</p><p className="mt-3 text-sm text-stone-600">{hospital.description || "Description not configured by hospital staff."}</p><Offerings title="Available specialists" icon={Stethoscope} items={hospital.specialist_profiles || []} kind="specialist" onBook={setBooking} /><Offerings title="Available treatments" icon={DollarSign} items={activeTreatments} kind="treatment" onBook={setBooking} /></section>{message && <p className="mt-4 rounded-lg bg-emerald-50 p-3 text-sm">{message}</p>}{booking && <BookingWindow hospital={hospital} currentUser={currentUser} booking={booking} onClose={() => setBooking(null)} onMessage={setMessage} />}</div>;
}

function Offerings({ title, icon: Icon, items, kind, onBook }) { return <section className="mt-7"><h2 className="flex items-center gap-2 font-semibold"><Icon className="h-4 w-4 text-emerald-700" />{title}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{items.length ? items.map((item) => { const price = kind === "specialist" ? item.consultation_fee : item.price; const schedules = kind === "specialist" ? futureSchedules((item.schedule || []).filter((schedule) => schedule.active !== false)) : []; return <article key={item.id} className="rounded-xl border p-4"><p className="font-semibold">{item.name}</p><p className="mt-1 text-sm text-stone-500">{item.specialization || item.description || "Details not configured."}</p><p className="mt-2 font-semibold text-emerald-700">{price != null ? `₹${price}` : "Price not configured"}</p>{kind === "specialist" && <div className="mt-3 text-xs text-stone-600"><p className="font-semibold">Available:</p>{schedules.length ? datesFor(schedules).map((date) => <p key={date}>{displayDate(date)}: {schedules.filter((schedule) => schedule.date === date).map((schedule) => `${prettyTime(schedule.start_time)} - ${prettyTime(schedule.end_time)}`).join(", ")}</p>) : <p>Availability not configured.</p>}</div>}<button disabled={price == null || (kind === "specialist" && !schedules.length)} onClick={() => onBook({ type: kind, item: { ...item, schedule: schedules } })} className="mt-3 rounded-lg bg-emerald-700 px-3 py-2 text-xs font-semibold text-white disabled:bg-stone-300">{kind === "specialist" ? "Book Specialist Appointment" : "Book Treatment"}</button></article>; }) : <p className="p-4 text-sm text-stone-500">No {kind === "specialist" ? "specialists" : "treatments"} currently available.</p>}</div></section>; }

function BookingWindow({ hospital, currentUser, booking, onClose, onMessage }) {
  const item = booking.item, specialistBooking = booking.type === "specialist";
  const schedules = specialistBooking ? (item.schedule || []).filter((schedule) => schedule.active !== false) : [];
  const dates = specialistBooking ? datesFor(schedules) : [];
  const [form, setForm] = useState({ name: currentUser?.username || "", phone: currentUser?.phone || "", email: currentUser?.email || "", date: "", time: "" });
  const [pending, setPending] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const times = specialistBooking ? timesFor(schedules, form.date) : [];
  const submit = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/bookings/discovery", { method: "POST", headers: headers(), body: JSON.stringify({ user_id: currentUser?.id, hospital_id: hospital.id, appointment_type: booking.type, specialist_id: specialistBooking ? item.id : null, treatment_id: specialistBooking ? null : item.id, appointment_date: form.date, appointment_time: form.time, patient_name: form.name, phone: form.phone, email: form.email, notes: "" }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Could not create appointment."); setPending(data); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  const pay = async () => { setBusy(true); try { const response = await fetch("/api/bookings/payments/verify", { method: "POST", headers: headers(), body: JSON.stringify({ booking_id: pending.id, payment_reference: `test_success_${Date.now()}` }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Payment verification failed."); onMessage(`Appointment confirmed. Payment status: ${data.paymentStatus}.`); onClose(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4"><div className="w-full max-w-lg rounded-2xl bg-white p-5"><div className="flex justify-between"><h2 className="text-lg font-semibold">{specialistBooking ? "Book specialist appointment" : "Book treatment"}</h2><button onClick={onClose}>Close</button></div>{pending ? <><p className="mt-4">Amount due: ₹{pending.amount}</p><button onClick={pay} disabled={busy} className="mt-5 w-full rounded-lg bg-emerald-700 px-4 py-3 text-white">{busy ? "Processing..." : `Pay ₹${pending.amount} (TEST)`}</button></> : <><div className="mt-4 grid gap-3 sm:grid-cols-2">{specialistBooking ? <><Field label="Available date"><select value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value, time: "" })} className="mt-1 w-full rounded border px-3 py-2 text-sm"><option value="">Select an available date</option>{dates.map((date) => <option key={date}>{date}</option>)}</select></Field><Field label="Available time"><select value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })} disabled={!form.date} className="mt-1 w-full rounded border px-3 py-2 text-sm"><option value="">Select an available time</option>{times.map((time) => <option key={time} value={time}>{prettyTime(time)}</option>)}</select></Field></> : <><Field label="Date"><input type="date" min={new Date().toISOString().slice(0, 10)} value={form.date} onChange={(e) => setForm({ ...form, date: e.target.value })} className="mt-1 w-full rounded border px-3 py-2 text-sm" /></Field><Field label="Time"><input type="time" value={form.time} onChange={(e) => setForm({ ...form, time: e.target.value })} className="mt-1 w-full rounded border px-3 py-2 text-sm" /></Field></>}</div><p className="mt-3 font-semibold text-emerald-700">Amount: ₹{specialistBooking ? item.consultation_fee : item.price}</p><div className="mt-4 space-y-3"><Field label="Name"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="mt-1 w-full rounded border px-3 py-2 text-sm" /></Field><Field label="Phone"><input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="mt-1 w-full rounded border px-3 py-2 text-sm" /></Field><Field label="Email"><input value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className="mt-1 w-full rounded border px-3 py-2 text-sm" /></Field></div><button onClick={submit} disabled={busy || !form.date || !form.time || !form.name || !form.phone || !form.email || !currentUser?.id} className="mt-5 w-full rounded-lg bg-emerald-700 px-4 py-3 text-white disabled:bg-stone-300">{busy ? "Submitting..." : "Continue to Payment"}</button></>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}</div></div>;
}
